
include_directories(${HappyEngine_SOURCE_DIR}/HappyEngine/code/audio)
include_directories(${HappyEngine_SOURCE_DIR}/HappyEngine/code/containers)
include_directories(${HappyEngine_SOURCE_DIR}/HappyEngine/code/content)
include_directories(${HappyEngine_SOURCE_DIR}/HappyEngine/code/error)
include_directories(${HappyEngine_SOURCE_DIR}/HappyEngine/code/game)
include_directories(${HappyEngine_SOURCE_DIR}/HappyEngine/code/gui)
include_directories(${HappyEngine_SOURCE_DIR}/HappyEngine/code/graphics)
include_directories(${HappyEngine_SOURCE_DIR}/HappyEngine/code/io)
include_directories(${HappyEngine_SOURCE_DIR}/HappyEngine/code/math)
include_directories(${HappyEngine_SOURCE_DIR}/HappyEngine/code/networking)
include_directories(${HappyEngine_SOURCE_DIR}/HappyEngine/code/physics)
include_directories(${HappyEngine_SOURCE_DIR}/HappyEngine/code/tools)
include_directories(${HappyEngine_SOURCE_DIR}/HappyEngine/code/plugin)
                            